import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";


const dmsans = localFont({
  src: [
    {
      path: '../../public/fonts/DMSans-VariableFont_opsz,wght.ttf',
    
    },       
  ],
  variable: '--font-dmsans',
  display: 'swap',  
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gradient-to-br from-zinc-950 to-zinc-900 w-screen h-screen">
      <body className={dmsans.className}>{children}</body>
    </html>
  );
}
